version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=blexxy
      - MONGO_PASSWORD=love
    command: ["npm", "run", "dev"]
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=blexxy
      - MONGO_INITDB_ROOT_PASSWORD=love
